packages:
  # Core packages
  - 'packages/*'

  # Adapter packages
  - 'adapters/*'

  # Middleware packages
  - 'middleware/*'

  # Plugin packages
  - 'plugins/*'

  # Apps and examples (nested structure)
  - 'apps/**'

  # Shared configurations
  - 'configs/*'

  # Exclude non-package directories
