packages:
  # Core packages
  - 'packages/*'
  
  # Plugin packages (nested structure)
  - 'plugins/*'
  
  # Apps and examples (nested structure)
  - 'apps/**'
  
  # Shared configurations
  - 'configs/*'

  
# Exclude non-package directories
  - '!tests'
  - '!benchmarks'
  - '!tooling/scripts'
  - '!docs'