# Docker Compose Test Infrastructure for Redis Adapter Package
#
# This configuration provides an isolated Redis instance for integration testing.
# The adapter tests run against this Redis instance to validate all three adapters:
# EventBus, Cache, and Queue.
#
# Usage:
#   Start services:  docker-compose -f compose.test.yaml up -d
#   Stop services:   docker-compose -f compose.test.yaml down
#   Full cleanup:    docker-compose -f compose.test.yaml down -v
#
# Connection Details:
#   Redis: redis://localhost:6379
#   Database: 0 (default)
#   Password: None (development only)

services:
  # ==========================================================================
  # Redis Service
  # ==========================================================================
  redis:
    image: redis:8-alpine
    container_name: blaize-adapter-redis-test

    ports:
      - '6379:6379'

    # Health check ensures Redis is ready before tests run
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

    # Enable append-only file for data persistence during test runs
    command: redis-server --appendonly yes

    # Memory limit for testing environment
    deploy:
      resources:
        limits:
          memory: 256M

    # Restart policy for CI environments
    restart: unless-stopped

    networks: [blaize-adapter-redis-test]

# ==========================================================================
# Isolated Test Network
# ==========================================================================
# Prevents port conflicts with other package test environments
networks:
  blaize-adapter-redis-test:
    driver: bridge